### PR TITLE
handle invalid keywords field better

### LINKED ISSUE #14: better handling of invalid keywords field
Sometimes [people don't read the docs](https://github.com/domchristie/to-markdown/blob/9fe260ebd329ba267fdccb05f1e5a26b553bd319/package.json), and their keywords field isn't an array of strings. This causes a problem right now, because `"keywords": "markdown"` gets turned into:

```
  "keywords": {
    "0": "m",
    "1": "a",
    "2": "r",
    "3": "k",
    "4": "d",
    "5": "o",
    "6": "w",
    "7": "n"
  }
```

...which feels significantly less fixed :P

### PR DESCRIPTION
**Pull request by slang800**
closes #14

### CODE REVIEW

**Comment by hhsnopek** [comment]
:+1:

**Comment by slang800** [comment]
@HenrikJoreteg - this is rebased now, if you're at all interested.

**Comment by HenrikJoreteg** [comment]
Nice! Looks good, but only thing i don't get is why you turned the config into json? it's not re-used anywhere, it's not read by anything else, it's just a way to load up a default config, right?

**Comment by HenrikJoreteg** [comment]
Also, last thing I want to do is get in your way of making this better, so... have at it :) I made you a contributor and gave you npm publish rights. merge/publish at will.

**Comment by slang800** [comment]
Cool, thanks!

And the reason for turning the config into JSON is just because it's a more strict language. In theroy, it should be parsed faster and should make it obvious that arbitrary logic isn't to be defined in the config. YAML or something like that would work equally well, but this being a node project, JSON seemed fitting.

**Comment by HenrikJoreteg** [comment]
works for me, ship away!

**Comment by slang800** [comment]
Shipped! I made it as a patch version because I don't think that anyone would consider the behavior described in #14 to be a part of the API.

PS: I've also started on some more new features over in https://github.com/slang800/fixpack, including license code correction, basic field misspelling correction (based on data from the npm database), tests, and version field cleaning.

**Pull request merged**
