### PR TITLE
Use modern JS syntax

### PR DESCRIPTION
**Pull request by JamieMason**
Hey @HenrikJoreteg,
I've been using `fixpack` for a few years now and love it. As a way of saying thanks I've put together this PR so you can use modern JS syntax transparently. When you run `npm pack` or `npm publish` it will automatically transpile `src/` into `dist/` and publish `dist/`. You can also run `npm run build` at any time and `node dist/bin.js` to run `fixpack` in development.

To test it out you can run

```
npm install
npm pack
npm install -g ./fixpack-2.3.0.tgz
fixpack
npm uninstall -g ./fixpack-2.3.0.tgz
rm ./fixpack-2.3.0.tgz
```

If you don't need/want this don't worry, it didn't take long.

Thanks again for fixpack :+1:

### CODE REVIEW

**Comment by luftywiranda13** [comment]
I'm sorry but this will add complexities to a pretty simple codebase in this project, won't it? look at the diffs

**Comment by slang800** [comment]
Interesting idea, but way out of scope for this tool. You should make this into a separate build tool that can be used independently of fixpack.

**Comment by HenrikJoreteg** [comment]
Thanks for taking the time, but I don't feel there's a need for introducing babel and a build step, given how small/simple this is. Thanks regardless, glad you've been enjoying this little utility. Cheers!

**Comment by JamieMason** [comment]
No worries, thanks @HenrikJoreteg 👍

**Pull request closed without merging**
